services:
  postgres:
    image: postgres:15
    container_name: saas-postgres
    environment:
      POSTGRES_USER: saas_admin
      POSTGRES_PASSWORD: saas_password
      POSTGRES_DB: saas_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: saas-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: saas-app
    environment:
      DATABASE_URL: postgresql://saas_admin:saas_password@postgres:5432/saas_chat
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run dev  # 👈 This ensures it runs nodemon inside docker (hot reload)

volumes:
  postgres-data:
